// build.rs
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let plugins_dir = Path::new("plugins");
    let mod_file = plugins_dir.join("mod.rs");
    let registry_file = Path::new("src/plugin_registry.rs");

    // Tell Cargo to rerun if these directories/files change
    println!("cargo:rerun-if-changed=plugins/");
    println!("cargo:rerun-if-changed=src/plugin_registry.rs");

    if !plugins_dir.exists() {
        fs::create_dir_all(plugins_dir).unwrap();
    }

    let mut modules = Vec::new();

    // Read all .rs files in plugins directory
    if let Ok(entries) = fs::read_dir(plugins_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() {
                if let Some(filename) = path.file_name() {
                    let filename_str = filename.to_string_lossy();
                    // Skip mod.rs itself and non-rust files
                    if filename_str.ends_with(".rs") && filename_str != "mod.rs" {
                        let module_name = filename_str.trim_end_matches(".rs");
                        modules.push(module_name.to_string());
                    }
                }
            }
        }
    }

    // Sort for consistent output
    modules.sort();

    // Generate mod.rs content
    generate_mod_rs(&mod_file, &modules);
    
    // Update plugin_registry.rs
    update_plugin_registry(&registry_file, &modules);
}

fn generate_mod_rs(mod_file: &Path, modules: &[String]) {
    let mut content = String::from("// Auto-generated by build.rs\n\n");
    for module in modules {
        content.push_str(&format!("pub mod {};\n", module));
    }

    let mut file = fs::File::create(mod_file).unwrap();
    file.write_all(content.as_bytes()).unwrap();
    println!("Generated plugins/mod.rs with {} modules", modules.len());
}

fn update_plugin_registry(registry_file: &Path, modules: &[String]) {
    // Read the existing file
    let content = fs::read_to_string(registry_file)
        .expect("Failed to read plugin_registry.rs");

    // Generate the use statements
    let mut use_statements = String::new();
    for module in modules {
        use_statements.push_str(&format!("use crate::plugins::{};\n", module));
    }

    // Generate the __register_all__ function body
    let mut register_body = String::new();
    for module in modules {
        let struct_name = to_pascal_case(module);
        register_body.push_str(&format!(
            "        self.register::<{}::{}>();\n",
            module, struct_name
        ));
    }

    // Replace the use section
    let new_content = replace_section(
        &content,
        "// Auto Generated: use",
        "// End Auto Generated: use",
        &use_statements
    );

    // Replace the register_all section
    let new_content = replace_section(
        &new_content,
        "// Auto Generated: register_all",
        "// End Auto Generated: register_all",
        &format!("    #[allow(unused_mut)]\n    fn register_all(&mut self) {{\n{}    }}", register_body)
    );

    // Write back to file
    fs::write(registry_file, new_content)
        .expect("Failed to write plugin_registry.rs");
    
    println!("Updated plugin_registry.rs with {} plugin registrations", modules.len());
}

fn replace_section(content: &str, start_marker: &str, end_marker: &str, new_content: &str) -> String {
    if let Some(start_pos) = content.find(start_marker) {
        if let Some(end_pos) = content.find(end_marker) {
            let before = &content[..start_pos + start_marker.len()];
            let after = &content[end_pos..];
            return format!("{}\n{}\n{}", before, new_content, after);
        }
    }
    eprintln!("Warning: Could not find markers '{}' and '{}'", start_marker, end_marker);
    content.to_string()
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<String>() + "Plugin"
}